# Generated by Django 3.2.13 on 2022-05-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifcation_type',
            new_name='notification_type',
        ),
    ]
